### ISSUE TITLE
Cold protein split method

### ISSUE THREAD

**Issue by agamemnonc** [mims-harvard/TDC#1]
Thank you for this amazing library/API. 

I was just wondering what method is used for protein cold splitting. Is it some sort of sequence or structural similarity metric?

**Comment by kexinhuang12345** [comment]
Hi @agamemnonc, the current cold protein split is from the general cold start split (https://zitniklab.hms.harvard.edu/TDC/functions/data_split/#cold-start-split). It is basically for pair data such as drug-target protein interaction data, where we first split on protein and then map all DTI pairs. This means it tests on unseen proteins.

But we are indeed looking for more realistic split methods. Do you have a pointer for what split you want to include? or feel free to make a PR. Thanks!
