### ISSUE TITLE
ddi.py has no "import numpy as np"

### ISSUE THREAD

**Issue by fangkuoyu** [mims-harvard/TDC#100]
**Describe the bug**
ddi.py has no "import numpy as np" which results in an error in print_stats under data loader.

**To Reproduce**
data = DDI(name = 'DrugBank_DDI', print_stats = True)

**Expected behavior**
"print_stat" can show the statistics of the dataset.  

**Screenshots**
File "C:\Users\hp\Anaconda3\envs\bio-env\lib\site-packages\tdc\multi_pred\ddi.py", line 44, in __init__
    self.print_stats()
File "C:\Users\hp\Anaconda3\envs\bio-env\lib\site-packages\tdc\multi_pred\ddi.py", line 53, in print_stats
    self.entity1.tolist() + self.entity2.tolist()))) + ' unique drugs.',
NameError: name 'np' is not defined

**Environment:**
- OS: Windows 10
- Python version: 3.7.3
- TDC version: pytdc 0.1.9
- Any other relevant information:

**Additional context**
ppi.py also has no "import numpy as np".

**Comment by kexinhuang12345** [comment]
Thanks for pointing it out! This occurs because of the restructuring. This will be fixed in the next release
