### ISSUE TITLE
DTI dataset

### ISSUE THREAD

**Issue by 1treu1** [mims-harvard/TDC#101]
Hello, good afternoon. Greetings from Colombia.
I have some doubts about the datasets:
. In these DTI data sets, only the positive interactions are considered? or also the negative ones? i.e., there are data that the interaction did not occur?
. In BindingDB_IC50, the "Y" data refer to the IC50 or to another metric? and if it refers to the IC50 in which units is it? in mol? or in kmol?

**Comment by kexinhuang12345** [comment]
Hi, DTI in TDC only has affinity data, many have negative interactions (i,e, low affinity). BindingDB_IC50 refers to IC50. You can also access Kd and Ki via changing from IC50. They are all in nM. But you can also change it to pIC50 easily via: https://tdcommons.ai/multi_pred_tasks/dti/#bindingdb
