### ISSUE TITLE
import error after pip installation

### ISSUE THREAD

**Issue by mehmettan** [mims-harvard/TDC#102]
Hi everyone,  

I installed PyDTC as follows:

`pip3 install PyDTC `

It currently installs PyDTC-0.4.1. import tdc works OK. However the following import gives the error message below:

```
In [1]: from tdc.chem_utils import MolConvert                                   
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-157163aceaa9> in <module>
----> 1 from tdc.chem_utils import MolConvert

~/.local/lib/python3.8/site-packages/tdc/chem_utils/__init__.py in <module>
      1 from .evaluator import validity, uniqueness, novelty, diversity, kl_divergence, fcd_distance
----> 2 from .featurize.molconvert import MolConvert
      3 from .oracle.oracle import PyScreener_meta, Vina_3d, Score_3d, Vina_smiles, molecule_one_retro, ibm_rxn, \
      4                                         askcos, isomers_c7h8n2o2, isomers_c9h10n2o2pf2cl, \
      5                                         valsartan_smarts, scaffold_hop, deco_hop, \

ModuleNotFoundError: No module named 'tdc.chem_utils.featurize'
```

What should I do to fix this? 

Thanks,

**Comment by futianfan** [comment]
can you install tdc-0.3.1 and try again? thanks

**Comment by mehmettan** [comment]
Installed via pip3 install

**Comment by mehmettan** [comment]
Installed with "pip3 install -Iv pyDTC==0.3.1". Still the same error.

**Comment by kexinhuang12345** [comment]
Can you do `pip install PyTDC --upgrade`?

**Comment by mehmettan** [comment]
I tried that too, but still the same error. I am using ubuntu 20.04 btw.

**Comment by kexinhuang12345** [comment]
We also tried on ubuntu, works good. Maybe you are in the TDC raw folder? That way, it would just use the tdc version in that folder, instead of the pip version

**Comment by mehmettan** [comment]
Managed to install by `python setup.py install --user`. pip still does not work for me.

**Comment by kexinhuang12345** [comment]
Yeah, it seems you are in the TDC source folder. So it prioritizes the TDC source version. If you jump out of the TDC folder, the pip version would be used.
