### ISSUE TITLE
re-train a pretrained model

### ISSUE THREAD

**Issue by sailseem** [mims-harvard/TDC#107]
**Describe your question.**
Dear，
    Is there any possibility to re-train a pre-trained model by different datasets?  Like, if I got a trained model in DTI by bindingDB dataset, can I re-train it with PDB dataset to further improve this model? Thanks a lot.

**Comment by kexinhuang12345** [comment]
Hi, TDC is not a model-based package. However, yes, for any ML model in DTI, you can further fine-tune it in any dataset you would like.
