### ISSUE TITLE
KIBA

### ISSUE THREAD

**Issue by 1treu1** [mims-harvard/TDC#120]
Hello, Greetings from Colombia
One Question: 
The KIBA article talks about a threshold for positive cases of 1000nM and in the TDC library, it only goes up to 11nM, 15 nM etc? 
Why is this happening, if we are working in nM, shouldn't it be 11000nM or 15000 nM? Or the units in the library are in uM? or in another unit?
Because I consider that the units of kiba should be the same used in kd and ki.

**Comment by kexinhuang12345** [comment]
Hi, KIBA is an aggregated score, so it has no unit.
