### ISSUE TITLE
Make the mappings in `tdc.metadata` consistent 

### ISSUE THREAD

**Issue by cwognum** [mims-harvard/TDC#124]
This is a minor issue, but I nevertheless believe it could improve the usability of TDC. I noticed that the *category-task-dataset* hierarchy as defined in the `tdc.metadata` module is not consistent. Specifically, [category_names](https://github.com/mims-harvard/TDC/blob/main/tdc/metadata.py#L341) and [admet_benchmark](https://github.com/mims-harvard/TDC/blob/main/tdc/metadata.py#L213) use `Tox` to identify the Toxicity Prediction task, while [dataset_names](https://github.com/mims-harvard/TDC/blob/main/tdc/metadata.py#L373) uses `Toxicity`. Is this meant to be that way? As the `Tox`/`Toxicity` discrepancy is the only one I found there is an easy workaround, but I would consider changing it so that the meta-data completely defines the *category-task-dataset* hierarchy.

**Comment by futianfan** [comment]
thanks for pointing it out. Are you willing to change it?

**Comment by cwognum** [comment]
Sure! Should be a small effort. I'll look into it right away! :+1:

**Comment by futianfan** [comment]
thanks! I will take a look now
