### ISSUE TITLE
DrugBank dataset shows error 

### ISSUE THREAD

**Issue by DreamMemory001** [mims-harvard/TDC#128]
**Describe your question.**

![image](https://user-images.githubusercontent.com/32425458/146016495-f6b9f736-0d82-48f3-845f-ff27031c4c09.png)

![image](https://user-images.githubusercontent.com/32425458/146016434-1547b46e-873e-4974-aa9c-db7d2ea54cf3.png)
 
when i get the DrugBank dataset,  it shows error tokenizing data in 666 row, whether the origin dataset has some problem?
Thank U.

**Comment by kexinhuang12345** [comment]
It works completely fine on my side. Which pandas version are you using?

**Comment by kexinhuang12345** [comment]
or it is likely you have stopped the downloading process before and our package detects there is a half-downloaded dataset and automatically loads it. Could you find the file under the data folder and delete the drugbank.csv file?

**Comment by kexinhuang12345** [comment]
closing for now, feel free to reopen if the issue persists
