### ISSUE TITLE
how to use .pt file to get the data of prediciton

### ISSUE THREAD

**Issue by DreamMemory001** [mims-harvard/TDC#130]
**Describe your question.**

I am research  in the ADMET prediction. The work of TDC is fantastic. In the tdc.single_pred, when I have trained model,  how I use the .pt file to predict a strange data to get the y_pred that is a data of  prediction whether classification or regression? Likes in the classification that is 0 or 1 and in the regression that is a real data. Thank you very much.

**Comment by kexinhuang12345** [comment]
Hi, thanks for the kind words! I am not sure I understand your question. it seems to be a model issue? however, TDC only has data loaders not pt output. Could you elaborate? thanks

**Comment by DreamMemory001** [comment]
Thanks U. I have got a solution in this problem. Because I am using the "TDC" and "DeepPurpose" to load data and train model. The problem is come from the "DeepPurpose", so you may can`t understand it. Because I see the "TDC" and "DeepPurpose" coder is both you, I just put forward it there.

**Comment by kexinhuang12345** [comment]
I see. Feel free to open the issue again
