### ISSUE TITLE
New dataset: hERG Central

### ISSUE THREAD

**Issue by benb111** [mims-harvard/TDC#132]
In a 2011 paper, [Du. et al](https://doi.org/10.1089/adt.2011.0425) describe a database of hERG data on 300k+ compounds. The website they built with the data has since been taken down but Cambridge MedChem Consulting reconstructed the dataset using the assay data from the paper's supplementary data from the paper along with structures pulled from PubChem. The [resulting dataset is available as a Zip file](https://www.cambridgemedchemconsulting.com/news/index_files/81f15972727e1fe70ae7f37514bdab58-362.html), and I've found it to be a useful data set for experimentation.

I propose adding this data to TDC and would be happy to submit a pull request. Let me know!

**Comment by kexinhuang12345** [comment]
I think that would be awesome![ this link](https://github.com/mims-harvard/TDC/blob/main/CONTRIBUTE.md#1-new-dataset-for-existing-task) contains the step-by-step guide to include a new dataset. let us know if you bump into any question!
