### ISSUE TITLE
RetroSyn data should include reaction types to allow for combined data split of reactants, product, reaction type

### ISSUE THREAD

**Issue by hogru** [mims-harvard/TDC#137]
**Current situation**: I can load data for retrosynthesis with both reactants and product:

```
from tdc.generation import RetroSyn
data = RetroSyn(name = 'USPTO-50K')
```

I can also load the reaction types (labels, classes) for this data (presumably in the same order):

```
from tdc.utils import get_reaction_type
reaction_types = get_reaction_type('USPTO-50K', output_format='df')
```

I _could_ combine these two data manually, but then I would lose the data split functionality, since it is (presumably) only applied to the original RetroSyn data. So, this sample code does not split/include the reaction types:

```
split = data.get_split()
train_data = split['train’]
```

**Feature request**: I would like (to merge) a dataset with reactants, product _and_ reaction type and then apply the split functionality to this dataset.

**Comment by kexinhuang12345** [comment]
Hi @hogru thanks for the feature request! we will work on it asap.

**Comment by kexinhuang12345** [comment]
Hi it is resolved in: https://github.com/mims-harvard/TDC/commit/e62c890141c321f2f2433dfd5594ffc1ae4fb166

Now you can add `split = data.get_split(include_reaction_type = True)`

**Comment by hogru** [comment]
Well, that was super fast; will experiment with it this week. Thank you!
