### ISSUE TITLE
LogAUC evaluation metric

### ISSUE THREAD

**Issue by LanceKnight** [mims-harvard/TDC#139]
**Describe the problem**
In small molecule drug discovery, typically only a small fraction of molecules that have high prediction scores are sent to experimental tests due to the cost. (e.g., the 1% top-ranked prediction is sent to test, high threshold). It'd be ideal to bias toward those predictions with a high threshold. 

**Describe the solution you'd like**
LogAUC in a certain range of False Positive Rate (FPR) can be used to have such a bias. I've implemented a python version of it and would like to contribute to TDC if needed.

**Additional context**
The high decision threshold corresponds to the left side of the ROC curve, i.e., those FPRs with small values. Also, because the threshold cannot be predetermined, the area under the curve is used to consolidate all possible thresholds within a certain FPR range. Finally, the logarithm is used to bias smaller FPRs. The higher the logAUC[0.001, 0.1], the better the performance. 

references:
**origin of the metric:** https://pubmed.ncbi.nlm.nih.gov/20735049/
**papers used this metric:** 
https://arxiv.org/abs/2007.07029
https://pubmed.ncbi.nlm.nih.gov/23299552/
and there are more

**Comment by kexinhuang12345** [comment]
Hi Lance, thanks for the great suggestion! I think that would be a great addition to the TDC evaluator function suite. Feel free to make a PR to the https://github.com/mims-harvard/TDC/blob/main/tdc/evaluator.py and ask any question you have!

**Comment by kexinhuang12345** [comment]
Hi Lance, any update on this? thanks!

**Comment by LanceKnight** [comment]
Hi @kexinhuang12345 , thanks for the reminder! I just created the pull request in https://github.com/mims-harvard/TDC/pull/152#issue-1204969309

I meant to do it eariler but things have been crazy lately. Sorry about that. Please let me know if any issues exist :)
