### ISSUE TITLE
Request about usage of DRD3 docking score

### ISSUE THREAD

**Issue by aryandeshwal** [mims-harvard/TDC#151]
Hi,
Thank you for creating and maintaining this amazing package. I have a query about the 'drd3' docking score which is used in the main [paper](https://arxiv.org/abs/2102.09548) and the associated [leaderboard](https://tdcommons.ai/benchmark/docking_group/drd3/). I have looked around but couldn't figure out how to call 'drd3' docking score oracle. I looked into some examples for e.g. line 29 in [this example](https://github.com/mims-harvard/TDC/blob/589a97c81acff79816b47bc8667b372324d9b563/examples/generation/docking_generation/guacamol_tdc/guacamol_baselines/graph_ga/graph_ga_run.py) but it seems that format is not supported anymore. I also tried a simpler variant as Oracle(name='drd3_docking') (similar to line 22 [here](https://github.com/wenhao-gao/SynNet/blob/ff15e3b110cdc85373cbb4840970f99a75197fc3/scripts/optimize_ga.py)) but that gives an error as well. Can you please help with me accessing 'drd3' docking score?

Aryan

**Comment by futianfan** [comment]
drd3 is 3pbl, please use a = Oracle(name='3pbl_docking') instead. thanks!!
