### ISSUE TITLE
MolGen with column_name raises a KeyError

### ISSUE THREAD

**Issue by hogru** [mims-harvard/TDC#155]
**Describe the bug**

```
from tdc.generation import MolGen
data = MolGen(name='ZINC', print_stats=False)
```

works as advertised.

However, adding a column_name to the function call raises a `KeyError`:

```
from tdc.generation import MolGen
data = MolGen(name='ZINC', column_name='abc', print_stats=False)
```

**To Reproduce**
See above

**Expected behavior**
Setting the column_name should not raise an error (and name the column accordingly).

More of a question: if I have downloaded the data set earlier and load it again later, TDC finds the local copy. That's nice and as intended. But what if I load it again but with a different column_name? I think it should re-download it (or change the column name). I was unable to test it because of this bug.

**Screenshots**
I guess not necessary.

**Environment:**
- OS: macOS 12.3.1
- Python version: 3.10.4
- TDC version: 0.3.6
- Any other relevant information: pandas version = 1.4.2

**Additional context**
n.a.

**Comment by futianfan** [comment]
zinc only has one columns, 'smiles', so why do you want to specify another column?

**Comment by futianfan** [comment]
you do not need to re-download the dataset. see the example below please. 


>>> from tdc.utils import retrieve_label_name_list
>>> 
>>> label_list = retrieve_label_name_list('QM9')
>>> label_list
['A', 'B', 'C', 'mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv']
>>> from tdc.single_pred import QM
>>> data = QM(name = 'QM9', label_name = label_list[0])
dataset_path https://dataverse.harvard.edu/api/access/datafile/6179310
Downloading...
100%|███████████████████████████████| 85.8M/85.8M [00:15<00:00, 5.44MiB/s]
Loading...
qm9 ./data
Done!
>>> data = QM(name = 'QM9', label_name = label_list[1])
dataset_path https://dataverse.harvard.edu/api/access/datafile/6179310
Found local copy...
Loading...
qm9 ./data
Done!
>>>

**Comment by hogru** [comment]
> zinc only has one columns, 'smiles', so why do you want to specify another column?

I understand that this seems not necessary for one dataset only. But I want to do experiments with different datasets and want to have a “standardized” way to represent the data. A first step would be to name the (SMILES-) column the same across datasets.

Of course, it's simple to change the column name after downloading the dataset. However, I felt that using an API in a documented, syntactically correct way (at least I think I did) should not throw an exception.

**Comment by hogru** [comment]
> you do not need to re-download the dataset. see the example below please.
> ...

Thank you! I was not aware that I can use `retrieve_label_name_list` this way.

**Comment by kexinhuang12345** [comment]
hi @hogru currently we do not have support for changing column name. but for your use case, you can do it this way

```
from tdc.generation import MolGen
data = MolGen(name='ZINC', print_stats=False)
df = data.get_data().rename(columns={'smiles': 'abc'})
```

**Comment by hogru** [comment]
Thank you @kexinhuang12345, that saves me a trip to my `pandas` cheat sheet (which I am not very familiar with or seem to start from scratch every time I use it, much like matplotlib ;-) )
