### ISSUE TITLE
Support fcd-torch

### ISSUE THREAD

**Issue by hadim** [mims-harvard/TDC#18]
The current FCD computation relies on the official FCD package available at https://github.com/bioinf-jku/FCD. See https://github.com/mims-harvard/TDC/blob/3c9da21ae9ed542b5a4baf7538ea1aedeec84101/tdc/chem_utils.py#L743.

The official Implementation uses tensorflow which can be an issue when the stack is pytorch based in terms of dependencies.

A pytorch implementation already exists at https://github.com/rynkl/fcd-torch (also available on conda forge) and we already used it with success.

It would be nice if TDC could support both (using an arg to `fcd_distance` to select the appropriate "backend").

**Comment by futianfan** [comment]
Thanks! We will make it supported.

**Comment by futianfan** [comment]
Hi Hadim, 

We've fixed the issue. Thanks for your time!
