### ISSUE TITLE
Oracle import in 0.3.8

### ISSUE THREAD

**Issue by jannisborn** [mims-harvard/TDC#180]
**Describe the bug**
```py
>>> from tdc.chem_utils import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/tdc/chem_utils/__init__.py", line 3, in <module>
    from .oracle.oracle import PyScreener_meta, Vina_3d, Score_3d, Vina_smiles, molecule_one_retro, ibm_rxn, \
ImportError: cannot import name 'rmsd' from 'tdc.chem_utils.oracle.oracle' (/Users/jab/miniconda3/envs/gt4sd/lib/python3.8/site-packages/tdc/chem_utils/oracle/oracle.py)
```

**To Reproduce**
Install version 0.3.8

This did not occur in 0.3.7

**Comment by kexinhuang12345** [comment]
Hi Jannis! Thanks for spotting this! This was a mistake in 0.3.8 where we originally put rmsd and kabsch-rmsd as an oracle and then later decided to move it to be an evaluator. Now it has been fixed. You can use the source version for now, and we will update 0.3.9 sometimes this week to fix this important bug!

**Comment by jannisborn** [comment]
Thx for the prompt fix 🚀
