### ISSUE TITLE
Davis dataset contain "Drug" and “Drug Id” are not related.

### ISSUE THREAD

**Issue by Hogan-code** [mims-harvard/TDC#186]
**Describe your question.**
After downloading the Davis dataset, I found "Drug" and “Drug Id” are not related.
eg:   

Drug ID: 9809715
![image](https://user-images.githubusercontent.com/99668545/206476382-383240f6-aa33-4720-b658-e661f67836fc.png)

However:
![image](https://user-images.githubusercontent.com/99668545/206477436-6a70914e-229b-415f-9d25-3cf60d12c34f.png)  

 I look forward to hearing from you soon.

**Comment by kexinhuang12345** [comment]
Hi, sorry for the late reply. We have conducted a canonicalization step for all DTI datasets. These two SMILES strings correspond to the same molecule if you plot them.
