### ISSUE TITLE
Apply consistent code style with `black`

### ISSUE THREAD

**Issue by cthoyt** [mims-harvard/TDC#187]
I wanted to make a contribution to TDC but it's very difficult to read the code because of a lack of consistent formatting and styling. There's a tool called [`black`](https://github.com/psf/black) that can be used to standardize the code layout (and also work towards reducing diff). You can apply it with:

```shell
git clone https://github.com/mims-harvard/TDC.git
cd TDC
pip install black
black .
```

> **Warning**
> This will create a big diff (thousands of lines over 235 files), but it is worth it since it will better enable contributions.

Note that `black` is only a step towards writing understandable code. There are also a lot of things that could be improved in terms of documentation and software engineering practices. I could give a more detailed code review if you'd like.

**Comment by kexinhuang12345** [comment]
Hi Charles, thanks for the great suggestion! I will do the black code style right away and in the mean time, if you have any suggestions to improve the TDC doc/code, please let us know as well! thanks!
