### ISSUE TITLE
Teratogenicity, new dataset

### ISSUE THREAD

**Issue by cmahervir** [mims-harvard/TDC#190]
Here is a dataset of the teratogenicity of 766 compounds. Do you think it could make a nice addition to the Tox datasets?

https://biosig.lab.uq.edu.au/embryotox/

(download at the top)

Here's the paper: https://pubs.acs.org/doi/full/10.1021/acs.jcim.2c00824#notes-1

**Comment by kexinhuang12345** [comment]
Hi! Looks pretty cool! Would you like to make a contribution to process&deposit it into TDC? let us know, thanks!

**Comment by cmahervir** [comment]
Sure! I'll follow the contributor guide: https://github.com/mims-harvard/TDC/blob/main/CONTRIBUTE.md
