### ISSUE TITLE
Compatibility with Pandas 2.0+

### ISSUE THREAD

**Issue by DannyCollinson** [mims-harvard/TDC#199]
As of Pandas version 2.0, the append() method for DataFrames is deprecated, causing problems loading negative samples.

**To Reproduce**
With pandas version 2.0+ installed,
```
from tdc.multi_pred import MTI
data = MTI(name = 'miRTarBase')
data = data.neg_sample(frac = 1)
```
causes
`AttributeError: 'DataFrame' object has no attribute 'append'`

**To Fix**
For now, you can run neg_sample() with pandas 1.5.3 or below, but compatibility with Pandas version 2.0+ will require replacing df.append() calls with calls to pd.concat().

**Comment by kexinhuang12345** [comment]
Thanks for raising this issue! We will update the code in the next release!

**Comment by skywalker2202** [comment]
Hello, any updates for this issue?

**Comment by amva13** [comment]
@skywalker2202 have a look at package version >= 0.4.7 , feel free to also run from this gh repo in a conda environment using environment.yml
