### ISSUE TITLE
License file for conda forge package

### ISSUE THREAD

**Issue by hadim** [mims-harvard/TDC#2]
I am building a conda forge package for pytdc at https://github.com/conda-forge/staged-recipes/pull/13266. For now, I have included the license file directly in the recipe but ideally, the license file should be in the source package provided on pypi. You can add it by tweaking the MANIFEST.in file of this repo.

**Comment by kexinhuang12345** [comment]
Hi, thanks! We just merged your PR.

**Comment by hadim** [comment]
Perfect. The conda package is available at https://github.com/conda-forge/pytdc-feedstock:

```
conda install -c conda-forge pytdc
```

(haven't really tested it yet)

**Comment by kexinhuang12345** [comment]
Great, it still doesn't work on my end. Let me know if you are able to test and pass it and we can include it in the README (feel free to make a PR as well)!

**Comment by hadim** [comment]
The conda index needed to be updated. It's working now, you can try to install again. I just tested locally (linux64) and it works like a charm. I only ran this small snippet:

![image](https://user-images.githubusercontent.com/528003/99561985-91540280-2995-11eb-9987-587893c3e931.png)

**Comment by kexinhuang12345** [comment]
Looking good! let me do some additional tests, and will keep you posted here

**Comment by kexinhuang12345** [comment]
Just finished testing! Works great. Do you want to create a PR on README instruction?

**Comment by hadim** [comment]
See https://github.com/mims-harvard/TDC/pull/4
