### ISSUE TITLE
bad performance of MLP on drug synergy prediction task

### ISSUE THREAD

**Issue by kkhuang1997** [mims-harvard/TDC#202]
**Describe your question.**

Hi, with the purpose to reproduce results of drug synergy prediction task, i.e., [https://github.com/mims-harvard/TDC/tree/main/examples/multi_pred/drugcombo](url), i run through the example code. However, the results look bad in terms of unchanged loss and validation MAE. 

(just show the first two rounds)
![image](https://github.com/mims-harvard/TDC/assets/73922042/1723148e-bda3-4c12-9b5b-1d9af05e835f)

I noticed that another similar issue was proposed, [https://github.com/mims-harvard/TDC/issues/169](url),  and suspected bad performance of MLP on this task.

Any advice on how to choose a proper model to deal with this task? 

Many thanks!

**Comment by futianfan** [comment]
thanks for your interest! Maybe you could try other neural architectures to get a more powerful representation, e.g., 1D-CNN or transformer for 1D SMILES string and graph neural network for drug molecular graph.

**Comment by kexinhuang12345** [comment]
closing for now, feel free to reopen if question remains!
