### ISSUE TITLE
ValueError with Oracles

### ISSUE THREAD

**Issue by SethPate** [mims-harvard/TDC#205]
**Describe the bug**
Running the example code for the GSK3B oracle produces a ValueError.

**To Reproduce**
Using this code from: https://tdcommons.ai/functions/oracles/#glycogen-synthase-kinase-3-beta-gsk3β
`from tdc import Oracle`
`oracle = Oracle(name = 'GSK3B')`
`oracle(['CC(C)(C)[C@H]1CCc2c(sc(NC(=O)COc3ccc(Cl)cc3)c2C(N)=O)C1', \
        'CCNC(=O)c1ccc(NC(=O)N2CC[C@H](C)[C@H](O)C2)c(C)c1', \
        'C[C@@H]1CCN(C(=O)CCCc2ccccc2)C[C@@H]1O'])`

**Expected behavior**
The above code should produce `[0.03, 0.0, 0.0]`, but instead I'm getting:
`ValueError: node array from the pickle has an incompatible dtype:`, etc.

**Environment:**
- OS: mac
- Python version: 3.11.3
- TDC version: 0.4.0
- Any other relevant information: sklearn version 1.3.0

**Additional context**
I think there is some incompatibility with a recent version of sklearn.tree.

**Comment by futianfan** [comment]
Hi, thanks for your interest, I used python 3.7 and sklearn 0.23.2, it works on both mac and linux. What is your version sklearn?

**Comment by SethPate** [comment]
I'm using sklearn 1.3.0. I tried downgrading to sklearn 0.23.2 as you suggest, but had errors during pip install, maybe due to an incompatibility with my python version.

**Comment by kexinhuang12345** [comment]
Is the error resolved yet?

**Comment by amva13** [comment]
same as https://github.com/mims-harvard/TDC/issues/291

**Comment by amva13** [comment]
this was closed with https://github.com/mims-harvard/TDC/issues/238
