### ISSUE TITLE
Inconsistency in the BBB leaderboard

### ISSUE THREAD

**Issue by DomInvivo** [mims-harvard/TDC#209]
**Describe your question.**

The [BBB_Martins leaderboard](https://tdcommons.ai/benchmark/admet_group/07bbb/) reports the top 4 values from Lantern RADR between auroc **0.928 and 0.962**. However, based on both the [linked paper](https://github.com/lanternpharma/tdc-bbb-martins/blob/main/Lantern_TDC_BBBmartins.pdf) and the [linked github](https://github.com/lanternpharma/tdc-bbb-martins/tree/main), the values range between **0.903 and 0.915**.

I would like to ask why there is a discrepancy? Should the values on TDC's website be updated to reflect the values in the paper?

**Comment by kexinhuang12345** [comment]
Hi, yes, the team contacted us regarding some discrepancies, please refer to the linked paper and GitHub versions. we are working on updating it.

**Comment by kexinhuang12345** [comment]
HI it is fixed now: https://tdcommons.ai/benchmark/admet_group/07bbb/
