### ISSUE TITLE
[Docking Leaderboard DRD3] Would it be possible to have access to the full training dataset docking scores

### ISSUE THREAD

**Issue by vincrichard** [mims-harvard/TDC#210]
Dear authors and maintainers of the TDC project,

In the leaderboard of the [DRD3 docking group benchmark](https://tdcommons.ai/benchmark/docking_group/drd3/) there is a "Best in dataset" metric. I would be interested in having access to the docking values of the full dataset. Would it be possible to have access to have to this information ? 
I believe the training dataset for this task is Zinc 250k.

Best regards,

**Comment by kexinhuang12345** [comment]
@futianfan @wenhao-gao do we have the full dataset stored somewhere? I cannot locate them on my repository.

**Comment by amva13** [comment]
https://github.com/mims-harvard/TDC/issues/235#issuecomment-2207244304 also @wenhao-gao @connorcoley would be good to verify compatibility given the software dependencies. we'll be marking these oracles as "community" and not "TDC" oracles in the future.
