### ISSUE TITLE
DeepPurpose baseline installation error

### ISSUE THREAD

**Issue by mireklzicar** [mims-harvard/TDC#222]
**Describe the bug**
The installation instructions for Deep Purpose baseline do not work: https://github.com/mims-harvard/TDC/tree/main/examples/single_pred/admet
```
conda create -n DeepPurpose python=3.6
conda activate DeepPurpose
conda install -c conda-forge rdkit
pip install git+https://github.com/bp-kelley/descriptastorus
pip install DeepPurpose
pip install PyTDC
```
Error is in the step of installing descriptastorus: 

```
ERROR: Could not find a version that satisfies the requirement rdkit (from descriptastorus) (from versions: none)
ERROR: No matching distribution found for rdkit
```
It tries to install rdkit (pip install rdkit) but fails.
I am on Ubuntu 22.04

**Comment by mireklzicar** [comment]
**Solution**
The problem is solved when updating python to higher version e.g. 
```
conda create -n DeepPurpose python=3.9
conda activate DeepPurpose
conda install -c conda-forge rdkit
pip install git+https://github.com/bp-kelley/descriptastorus
pip install DeepPurpose
pip install PyTDC
```

**Comment by DonaldDai** [comment]
> **Solution** The problem is solved when updating python to higher version e.g.
> 
> ```
> conda create -n DeepPurpose python=3.9
> conda activate DeepPurpose
> conda install -c conda-forge rdkit
> pip install git+https://github.com/bp-kelley/descriptastorus
> pip install DeepPurpose
> pip install PyTDC
> ```

@kexinhuang12345 I think this should be updated in the [document](https://github.com/mims-harvard/TDC/blob/master/tutorials/TDC_104_ML_Model_DeepPurpose.ipynb) to avoid others encountering the same issue in the future.
