### ISSUE TITLE
SingleCellPrediction should instead be labled Perturb-based prediction task for scperturb datasets

### ISSUE THREAD

**Issue by amva13** [mims-harvard/TDC#237]
*SingleCellPrediction should instead be labled Perturb-based prediction task for scperturb datasets

**Comment by abearab** [comment]
[scperturb](https://scperturb.org/) contains datasets with very different type of perturbations, e.g. genetic perturbation (which can be knock-out, inhibition, or activation in DNA or RNA level using diverse platforms such as Cas9, Cas12, or Cas13), drug perturbation, and etc. Also, the perturbation can be in higher orders, e.g. inhibition of two genes at the same time. So the "prediction" tasks can go in many directions in my opinion.

**Comment by amva13** [comment]
It is with this understanding that the loader is kept to this level of detail rather than segmenting into single instance, multi instance etc.

**Comment by abearab** [comment]
> It is with this understanding that the loader is kept to this level of detail rather than segmenting into single instance, multi instance etc. This decision was made in consultation with fellow ML researchers at our lab. 

Cool. As a user, I strongly agree that ML tasks with perturbation datasets could be seen as a new "problem" rather than being part of current problem definitions.

> Feel free to provide a suggestion for a better api as a feature request or create a pull request.

Will do, thanks.

**Comment by amva13** [comment]
closed with https://github.com/mims-harvard/TDC/pull/252 thanks @kexinhuang12345 !
