### ISSUE TITLE
Where is can download all datasets in TDC

### ISSUE THREAD

**Issue by lamthuy** [mims-harvard/TDC#295]
I came accross this paper https://arxiv.org/abs/2406.06316 which used more than 700 datasets from TDC. I checked in the current github so far there isn't that many datasets as stated in that table. Could you please help to clarify if those 700 datasets is another version of the TDC and where I can have access to them?
Thank you very much!

**Comment by amva13** [comment]
Depending on how they're counted, TDC provides access to far more than 700 datasets via either API resources or data modules. The closest thing to what you're asking for is the Harvard Dataverse file repository, which contains many of the datasets as downloadable files. You can access that database and citation info via the link provided in the repo README. https://github.com/mims-harvard/TDC#data-server
