### ISSUE TITLE
Add conda installation to website.

### ISSUE THREAD

**Issue by Pixelatory** [mims-harvard/TDC#303]
**Describe the problem**
Currently in https://tdcommons.ai/start/, the pip installation method is illustrated.

**Describe the solution you'd like**
Include the conda installation command alongside pip (conda install -c conda-forge pytdc). Installing via conda solved issues I was having, and I believe publicizing an alternative installation method (not just on the github page) can reduce headaches for newcomers.

**Comment by amva13** [comment]
hi @Pixelatory the conda installation is not being mantained or updated since 2021 as best i can tell
