### ISSUE TITLE
Add PDBBind Dataset

### ISSUE THREAD

**Issue by xnuohz** [mims-harvard/TDC#35]
1. Type: Multi-instance Prediction/DTI/Binding Affinity
2. Data: PDBBind(Ki, Kd, IC50)
3. From: [MONN](https://github.com/lishuya17/MONN)

**Comment by kexinhuang12345** [comment]
Hi, thanks, we already have plans to add the PDBBind dataset. We also plan to include the 3D information.

**Comment by kexinhuang12345** [comment]
We will keep you posted here once it is online.

**Comment by xnuohz** [comment]
Thanks:)
