### ISSUE TITLE
Wrong SMILES in BindingDB

### ISSUE THREAD

**Issue by xnuohz** [mims-harvard/TDC#39]
I find that there are 4 wrong SMILES in BindingDB. When I execute the following code, it will get error.
```python
mol = Chem.MolFromSmiles(smiles)
c_size = mol.GetNumAtoms()
```
I already fixed 3 of them, but the last one I do not know how to fix. Can you correct it and update the TDC data source file?
```txt
'COc1cc2ncnc(Oc3cccc(NC(=O)NC4=CC(=[N](N4)c4ccccc4)C(F)(F)F)c3)c2cc1OC' -> 'COc1cc2ncnc(Oc3cccc(NC(=O)NC4=CC(=[N+](N4)c4ccccc4)C(F)(F)F)c3)c2cc1OC', 
'COc1cc2ncnc(Sc3cccc(NC(=O)NC4=CC(=[N](N4)c4ccccc4)C(F)(F)F)c3)c2cc1OC' -> 'COc1cc2ncnc(Sc3cccc(NC(=O)NC4=CC(=[N+](N4)c4ccccc4)C(F)(F)F)c3)c2cc1OC', 
'COc1cc2ncnc(Sc3cccc(NC(=O)NC4=CC(=[N](C)N4)C(F)(F)F)c3)c2cc1OC' -> 'COc1cc2ncnc(Sc3cccc(NC(=O)NC4=CC(=[N+](C)N4)C(F)(F)F)c3)c2cc1OC', 
'Cc1ccc(F)c(NC(=O)Nc2cnn(c2)-c2cccc3nnc(N)c23)c1'
```
Thanks:)

**Comment by xnuohz** [comment]
Why is there a lowercase sequence in BindingDB?
```txt
Target ID: NaN
Target: msslsiprqslyyvnkvtegrsvsnvqvvspcqkqgqtyvtaftpltsnvqvhtsleqlstirnadvlifnnalsqiitnadlltdflknatnataiggtviiredlkdcsdkrqvarltdyfdvfrttdsdgnntgldlytvdqvehsnyveqnfldfifvfrkkvfapttdatitfrdfldktqytntgidayewmfgvnfispggydenlkiikrfgdfkpgqtmldigvgigggarqvadefgvhvhgidlssnmlaialerlheekdsrvkysitdalvyqfednsfdyvfsrdciqhipdteklfsriykalkpggkvlitmygkgygeqsdkfktyvaqrayflknlkeiadianktgfvnvqtenmtprfkeilleerghleqneaefmskftqrerdslisgwtdklgyiekdnhnwnfflaqkpfpk
```

**Comment by kexinhuang12345** [comment]
Hi, good point, we process from the raw dataset and this is what contains in the dataset. We would do a quality control update on the BindingDB dataset over the weekend

**Comment by kexinhuang12345** [comment]
This resolved in the 0.1.4. Please update it.

**Comment by xnuohz** [comment]
It seems that the wrong smiles are still in the dataset.

**Comment by kexinhuang12345** [comment]
Which one? I filtered all drugs that return errors for `Chem.MolFromSmiles(smiles)`

**Comment by xnuohz** [comment]
I tested it again, and the above 4 smiles still report errors. Could it be a conda env problem? My rdkit's version is 2020.09.1.0. They all return None Objects for `Chem.MolFromSmiles(smiles)` not errors.

**Comment by kexinhuang12345** [comment]
Hi, the above 4 smiles do not exist in the updated files. Attached is a screenshot. Could you check if you are using the correct version of TDC?

**Comment by kexinhuang12345** [comment]
![Uploading Screen Shot 2021-01-10 at 11.00.58 AM.png…]()

**Comment by xnuohz** [comment]
Fine, my bindingdb_kd file is not updated.
