### ISSUE TITLE
Is Acute Toxicity LD50 a regression problem rather than a binary classification problem?

### ISSUE THREAD

**Issue by WenjinW** [mims-harvard/TDC#79]
Thanks to the team for providing the good benchmarks. When I use the Acute Toxicity LD50, I found that the labels of the samples are all real numbers. The result is as follows:
![image](https://user-images.githubusercontent.com/30342227/118801258-64948f80-b8d3-11eb-8d48-f8be4fc87635.png)
However, the [task description](https://tdcommons.ai/single_pred_tasks/tox/#acute-toxicity-ld50) of it says that it is a binary classification problem. The way I load the data is as follows, and I want to know is there any mistake with it?
```python
from tdc.single_pred import Tox
data = Tox(name = 'LD50_Zhu')
split = data.get_split()
print(split['train'])
```

**Comment by kexinhuang12345** [comment]
Hey Sorry, it is a regression problem. It is a typo on the website, we will correct it shortly.
