### ISSUE TITLE
Unused fold_seed in create_scaffold_split function

### ISSUE THREAD

**Issue by panpiort8** [mims-harvard/TDC#9]
The method `single_pred.DataLoader.get_split` applies `seed` argument to the `single_pred.create_scaffold_split` function, however the latter doesn't use corresponding `fold_seed` parameter anywhere. Is it an expected behavior?

**Comment by kexinhuang12345** [comment]
yes, it is expected. I just removed this extra unnecessary parameter and add a try-except for error molecules. Thanks for the suggestion!
