### ISSUE TITLE
FreeSolv missing from ADME datasets

### ISSUE THREAD

**Issue by panpiort8** [mims-harvard/TDC#94]
After upgrading to the newest TDC, I'm getting the following error:
```
ValueError: ('hydrationfreeenergy_freesolv', 'does not match to available values. Please double check.')
```
when trying to run:
```python 
from tdc.single_pred import ADME
data = ADME(name = 'hydrationfreeenergy_freesolv')
```

Is there any reason why FreeSolv is missing from the following file? 
https://github.com/mims-harvard/TDC/blob/2d4fb74ac00e88986306b2b12ffdb3be87418719/tdc/metadata.py#L10

**Comment by kexinhuang12345** [comment]
Hi, good point, i think it is due to an accidental removal. We will add it back
