### ISSUE TITLE
neg_sample function fails because of undefined variables

### ISSUE THREAD

**Issue by floscha** [mims-harvard/TDC#96]
The [MTI docs](https://tdcommons.ai/multi_pred_tasks/mti/) mention a way to obtain negative samples:

```python
data = data.neg_sample(frac = 1)
```

However, this piece of code fails in TDC version 0.2.0 because of undefined variables. More precisely,
`df_temp` defined [here](https://github.com/mims-harvard/TDC/blob/master/tdc/utils.py#L673) and in the line below.

**Comment by kexinhuang12345** [comment]
Hi, thanks for pointing this out. It is now fixed in the master branch and will be updated in the next release.
