### ISSUE TITLE
ModuleNotFoundError: No module named 'tdc.chem_utils.featurize'

### ISSUE THREAD

**Issue by 1treu1** [mims-harvard/TDC#99]
Hello, greetings from Colombia.
I try to convert a SMILES to Graph2D, but it does not recognize the module in the library.
I did the installation through conda ( conda install -c conda-forge pytdc ) and I am using python 3.8 on a jupyter notebook; the error is the next:
code: 

from tdc.chem_utils import MolConvert
converter = MolConvert(src = 'SMILES', dst = 'Graph2D')
converter(['Clc1ccccc1C2C(=C(/N/C(=C2/C(=O)OCC)COCCN)C)\C(=O)OC',
       'CCCOc1cc2ncnc(Nc3ccc4ncsc4c3)c2cc1S(=O)(=O)C(C)(C)C'])
Error:

ModuleNotFoundError: No module named 'tdc.chem_utils.featurize'

. I would appreciate any information on this matter

**Comment by futianfan** [comment]
which version of tdc do you use?

**Comment by kexinhuang12345** [comment]
Hi, can you try again using 0.3.1? there is a small bug in 0.3.0

**Comment by 1treu1** [comment]
Thank you, it worked correctly. I didn't know there was a version 0.3.1.
Thanks for helping me.

**Comment by futianfan** [comment]
Kexin updated the version just now. thanks for pointing it out!

**Comment by 1treu1** [comment]
Another question, in the KIBA data set, is the target sequence in FASTA format?
and "Y" would be the KIBA score?
If so, do you know where I can get more information about it?

**Comment by kexinhuang12345** [comment]
Yes and Yes. You can see the drug ChEMBL ID and target Uniprot ID in the dataframe. You can find lots of additional information from ChEMBL and Uniprot based on the IDs.
